baseURL = 'https://cmosinverter.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  env = 'production'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Welcome"
    Content = "A blog about technology and ideas."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/cmosinverter"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/cmosinverter"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:kevin95120@gmail.com"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20
